config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views


app_name = "conversations"

urlpatterns = [
    path("go/<int:host_pk>/<int:guest_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("toggle/<int:pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("", views.ReservationGuestView.as_view(), name="guest"),
    path("host/<int:pk>/", views.ReservationHostView.as_view(), name="host"),
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

lists/models.py
from django.db import models
from core import models as core_models


# Create your models here.
class List(core_models.TimeStampedModel):

    """List Model Definition"""

    name = models.CharField(max_length=80)
    user = models.OneToOneField(
        "users.User", related_name="list", on_delete=models.CASCADE
    )
    rooms = models.ManyToManyField("rooms.Room", related_name="list", blank=True)

    def __str__(self):
        return self.name

    def count_rooms(self):
        return self.rooms.count()

    count_rooms.short_description = "Number of Rooms"

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):

    day = models.DateField()
    reservation = models.ForeignKey("Reservatrion", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


# Create your models here.
class Reservatrion(core_models.TimeStampedModel):

    """Reservation Model Definition"""

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end)
            ).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

lists/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView
from django.contrib import messages
from users import mixins as user_mixins
from rooms import models as room_models
from . import models as list_models


def toggle_room(request, pk):
    action = request.GET.get("action", None)
    room = room_models.Room.objects.get_or_none(pk=pk)
    if room is not None and action is not None:
        the_list, _ = list_models.List.objects.get_or_create(
            user=request.user, name="My Favorites Houses"
        )
        if action == "add":
            the_list.rooms.add(room)
            messages.success(request, "Saved to Favorites")
        elif action == "remove":
            the_list.rooms.remove(room)
            messages.success(request, "Removed from Favorites")

    return redirect(reverse("rooms:detail", kwargs={"pk": pk}))


class SeeFavsView(user_mixins.LoggedInOnlyView, TemplateView):
    template_name = "lists/list_detail.html"

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View, ListView
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from users import mixins as user_mixins
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve that Room!")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservatrion.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(user_mixins.LoggedInOnlyView, View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservatrion.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = review_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservatrion.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservatrion.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservatrion.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated!")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationGuestView(user_mixins.LoggedInOnlyView, ListView):
    model = models.Reservatrion
    template_name = "reservations/list.html"
    context_object_name = "reservations"

    def get(self, request, *args, **kwargs):
        user = request.user
        object_list = self.get_queryset()
        self.object_list = object_list.filter(guest=user)
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(
                self.object_list, "exists"
            ):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        context = self.get_context_data()
        return self.render_to_response(context)


class ReservationHostView(user_mixins.LoggedInOnlyView, ListView):
    pass

templates/reservations/detail.html
{% extends 'base.html' %}

{% block page_title %}
    Rservation {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container mx-auto my-10 flex flex-col">
        <div class="bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});"></div>

        <div class="flex flex-col items-start border">
            <div class="font-semibold border-b py-8 px-5 w-full">
                {{reservation.check_in}} - {{reservation.check_out}} <span class="ml-5 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-500 {% else %} text-green-500 {% endif %}">{{reservation.get_status_display}}</span>
            </div>
    
            <span class="text-2xl border-b mt-2 p-5 w-full font-bold">
                {{reservation.room.name}}
            </span>
    
            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% include 'mixins/user_avatar.html' with user=reservation.room.host %}
                    <span class="mt-2 text-gray-500">{{reservation.room.host.first_name}}</span>
                </div>
                <div class="ml-5 flex flex-col">
                    <span class="font-medium mb-px">Contact your Airbnb Host</span>
                    <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="font-medium text-green-500 hover:underline">Send a Message</a>
                </div>
            </div>
            
            <div class="py-10 px-5">
                {% if reservation.status != 'canceled' %}
                    {% if reservation.status == 'confirmed' and reservation.is_finished %}
                        <span class="font-semibold text-2xl text-center block mb-5">Write your review</span>
                        <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto">
                            {% csrf_token %}
                            {{form}}
                            <button class="btn-link mt-5">Submit Review</button>
                        </form>
                    {% else %}
                            {% if reservation.status == 'pending' %}
                                {% if reservation.room.host == user %}
                                    <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link block px-5 mb-5">Confirm Reservation</a>
                                {% endif %}
                                <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link block px-5">Cancel Reservation</a>
                            {% endif %}
                    {% endif %}
                {% endif %}
            </div>
            
        </div>
        
    </div>

{% endblock content %}

templates/reservations/list.html
{% extends 'base.html' %}

{% block page_title %}
    {{user.first_name}}'s Reservations
{% endblock page_title %}


{% block content %}
    
    {% if  reservations.count > 0 %}
        <div class="container flex flex-col items-center mx-auto pb-10">
            <h3 class="mb-12 text-2xl">{{user.first_name}}'s Reservations</h3>
            <div class="w-3/4 flex flex-wrap mb-10">
                {% for reservation in reservations %}
                        {% include 'mixins/room_card.html' with room=reservation.room reservation=reservation %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
        

{% endblock content %}